// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(s_axi_aclk,0,0);
        VL_IN8(s_axi_aresetn,0,0);
        VL_IN8(s_axi_awprot,2,0);
        VL_IN8(s_axi_awvalid,0,0);
        VL_OUT8(s_axi_awready,0,0);
        VL_IN8(s_axi_wstrb,3,0);
        VL_IN8(s_axi_wvalid,0,0);
        VL_OUT8(s_axi_wready,0,0);
        VL_OUT8(s_axi_bresp,1,0);
        VL_OUT8(s_axi_bvalid,0,0);
        VL_IN8(s_axi_bready,0,0);
        VL_IN8(s_axi_arprot,2,0);
        VL_IN8(s_axi_arvalid,0,0);
        VL_OUT8(s_axi_arready,0,0);
        VL_OUT8(s_axi_rresp,1,0);
        VL_OUT8(s_axi_rvalid,0,0);
        VL_IN8(s_axi_rready,0,0);
        VL_OUT8(intr,0,0);
        CData/*0:0*/ gpio_axi__DOT__s_axi_aclk;
        CData/*0:0*/ gpio_axi__DOT__s_axi_aresetn;
        CData/*2:0*/ gpio_axi__DOT__s_axi_awprot;
        CData/*0:0*/ gpio_axi__DOT__s_axi_awvalid;
        CData/*0:0*/ gpio_axi__DOT__s_axi_awready;
        CData/*3:0*/ gpio_axi__DOT__s_axi_wstrb;
        CData/*0:0*/ gpio_axi__DOT__s_axi_wvalid;
        CData/*0:0*/ gpio_axi__DOT__s_axi_wready;
        CData/*1:0*/ gpio_axi__DOT__s_axi_bresp;
        CData/*0:0*/ gpio_axi__DOT__s_axi_bvalid;
        CData/*0:0*/ gpio_axi__DOT__s_axi_bready;
        CData/*2:0*/ gpio_axi__DOT__s_axi_arprot;
        CData/*0:0*/ gpio_axi__DOT__s_axi_arvalid;
        CData/*0:0*/ gpio_axi__DOT__s_axi_arready;
        CData/*1:0*/ gpio_axi__DOT__s_axi_rresp;
        CData/*0:0*/ gpio_axi__DOT__s_axi_rvalid;
        CData/*0:0*/ gpio_axi__DOT__s_axi_rready;
        CData/*0:0*/ gpio_axi__DOT__intr;
        CData/*0:0*/ gpio_axi__DOT__reg_we;
        CData/*0:0*/ gpio_axi__DOT__reg_re;
        CData/*3:0*/ gpio_axi__DOT__reg_be;
        CData/*0:0*/ gpio_axi__DOT__reg_ack;
        CData/*0:0*/ gpio_axi__DOT__aw_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__we;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__re;
        CData/*3:0*/ gpio_axi__DOT__u_gpio_regs__DOT__be;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ack;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__intr;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__0__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__1__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__2__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__3__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__4__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__5__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__6__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__7__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__8__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__9__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__10__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__11__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__12__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__13__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__14__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__15__KET____DOT__gpio_i_sync;
    };
    struct {
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pull_up_en;
    };
    struct {
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__i;
    };
    struct {
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__s_axi_aclk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__s_axi_aresetn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_regs__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_regs__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__reset_n__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_axi__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        VL_INOUT16(io,15,0);
        SData/*15:0*/ gpio_axi__DOT__io;
        SData/*15:0*/ gpio_axi__DOT__reg_data_o;
        SData/*15:0*/ gpio_axi__DOT__reg_dir;
        SData/*15:0*/ gpio_axi__DOT__gpio_i;
        SData/*15:0*/ gpio_axi__DOT__open_drain;
        SData/*15:0*/ gpio_axi__DOT__pull_up_en;
        SData/*15:0*/ gpio_axi__DOT__pull_down_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__reg_data_o;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__reg_dir;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_i;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__open_drain;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pull_up_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pull_down_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_data_o;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_dir;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_int_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_int_typ;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_int_pol;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_int_any;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_int_sts;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_deb_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_inv_in;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_inv_out;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_od_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_wr_mask;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_pu_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_pd_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_pwm_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pwm_cnt;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pwm_prescaler;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pwm_val;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_i_deb;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_i_deb_q;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_edge_pos;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_edge_neg;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gpio_edge_any;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_regs__DOT__intr_cond;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__o;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__oe;
    };
    struct {
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__i;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__open_drain;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__pull_up_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__pull_down_en;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out16;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out17;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out18;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out19;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out20;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out21;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out22;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out23;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out24;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out25;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out26;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out27;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out28;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out29;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out30;
        SData/*15:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__io__out__strong__out31;
        VL_IN(s_axi_awaddr,31,0);
        VL_IN(s_axi_wdata,31,0);
        VL_IN(s_axi_araddr,31,0);
        VL_OUT(s_axi_rdata,31,0);
        IData/*31:0*/ gpio_axi__DOT__s_axi_awaddr;
        IData/*31:0*/ gpio_axi__DOT__s_axi_wdata;
        IData/*31:0*/ gpio_axi__DOT__s_axi_araddr;
        IData/*31:0*/ gpio_axi__DOT__s_axi_rdata;
        IData/*31:0*/ gpio_axi__DOT__reg_addr;
        IData/*31:0*/ gpio_axi__DOT__reg_wdata;
        IData/*31:0*/ gpio_axi__DOT__reg_rdata;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__addr;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__wdata;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__rdata;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_deb_th;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__s_reg_pwm_cfg;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pwm_duty_idx;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__pwm_duty_int;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__0__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__1__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__2__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__3__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__4__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__5__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__6__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__7__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__8__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__9__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__10__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__11__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__12__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__13__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__14__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__gen_deb__BRA__15__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk2__DOT__r;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk3__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk4__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk5__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk7__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk8__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk9__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk10__DOT__k;
    };
    struct {
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk11__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk12__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk14__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk15__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk16__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk17__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk18__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk19__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk20__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_reg_read__DOT__unnamedblk21__DOT__k;
        IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__proc_intr_out__DOT__unnamedblk22__DOT__m;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 16> gpio_axi__DOT__u_gpio_regs__DOT__s_reg_pwm_duty;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 16>, true, SData/*15:0*/, 1> __VdlyCommitQueuegpio_axi__DOT__u_gpio_regs__DOT__s_reg_pwm_duty;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_DATA_I = 0U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_DATA_O = 4U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_DIR = 8U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INT_EN = 0x0cU;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INT_TYP = 0x10U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INT_POL = 0x14U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INT_ANY = 0x18U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INT_STS = 0x1cU;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_SET_O = 0x20U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_CLR_O = 0x24U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_TGL_O = 0x28U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_DEB_TH = 0x2cU;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_DEB_EN = 0x30U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INV_IN = 0x34U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_INV_OUT = 0x38U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_OD_EN = 0x3cU;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_WR_MASK = 0x40U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_PU_EN = 0x44U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_PD_EN = 0x48U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_PWM_EN = 0x4cU;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_PWM_CFG = 0x50U;
    static constexpr CData/*6:0*/ gpio_axi__DOT__u_gpio_regs__DOT__ADDR_PWM_DUTY = 0x54U;
    static constexpr IData/*31:0*/ gpio_axi__DOT__NUM_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpio_axi__DOT__u_gpio_regs__DOT__NUM_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpio_axi__DOT__u_gpio_wrapper__DOT__NUM_BITS = 0x00000010U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
