// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(pclk,0,0);
        VL_IN8(presetn,0,0);
        VL_IN8(psel,0,0);
        VL_IN8(penable,0,0);
        VL_IN8(pwrite,0,0);
        VL_IN8(pstrb,3,0);
        VL_OUT8(pready,0,0);
        VL_OUT8(pslverr,0,0);
        VL_OUT8(intr,0,0);
        CData/*0:0*/ gpio_apb__DOT__pclk;
        CData/*0:0*/ gpio_apb__DOT__presetn;
        CData/*0:0*/ gpio_apb__DOT__psel;
        CData/*0:0*/ gpio_apb__DOT__penable;
        CData/*0:0*/ gpio_apb__DOT__pwrite;
        CData/*3:0*/ gpio_apb__DOT__pstrb;
        CData/*0:0*/ gpio_apb__DOT__pready;
        CData/*0:0*/ gpio_apb__DOT__pslverr;
        CData/*0:0*/ gpio_apb__DOT__intr;
        CData/*0:0*/ gpio_apb__DOT__reg_we;
        CData/*0:0*/ gpio_apb__DOT__reg_re;
        CData/*3:0*/ gpio_apb__DOT__reg_be;
        CData/*0:0*/ gpio_apb__DOT__reg_ack;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__we;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__re;
        CData/*3:0*/ gpio_apb__DOT__u_gpio_regs__DOT__be;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ack;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__intr;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__0__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__1__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__2__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__3__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__4__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__5__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__6__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__7__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__8__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__9__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__10__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__11__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__12__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__13__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__14__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__15__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__16__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__17__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__18__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__19__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__20__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__21__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__22__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__23__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__24__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__25__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__26__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__27__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__28__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__29__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__30__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__31__KET____DOT__gpio_i_sync;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__clk;
    };
    struct {
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__oe_actual;
    };
    struct {
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pull_down_en;
    };
    struct {
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__open_drain;
    };
    struct {
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__oe;
    };
    struct {
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__reset_n;
    };
    struct {
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__clk;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__reset_n;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__o;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__oe;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__i;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__open_drain;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__pull_up_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__pull_down_en;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__pad;
        CData/*0:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__oe_actual;
        CData/*1:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__sync_reg;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_regs__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_regs__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__0__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__1__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__2__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__3__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__4__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__5__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__6__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__7__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__8__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__9__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__10__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__11__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__12__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__13__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__clk__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__14__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__15__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__16__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__17__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__18__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__19__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__20__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__21__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__22__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__23__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__24__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__25__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__26__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__27__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__28__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__29__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__30__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpio_apb__DOT__u_gpio_wrapper__DOT__gen_gpio_bits__BRA__31__KET____DOT__u_gpio_bit__DOT__reset_n__0;
        SData/*15:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pwm_cnt;
        SData/*15:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pwm_prescaler;
        VL_IN(paddr,31,0);
        VL_IN(pwdata,31,0);
        VL_OUT(prdata,31,0);
        VL_INOUT(io,31,0);
        IData/*31:0*/ gpio_apb__DOT__paddr;
        IData/*31:0*/ gpio_apb__DOT__pwdata;
        IData/*31:0*/ gpio_apb__DOT__prdata;
        IData/*31:0*/ gpio_apb__DOT__io;
        IData/*31:0*/ gpio_apb__DOT__reg_addr;
        IData/*31:0*/ gpio_apb__DOT__reg_wdata;
        IData/*31:0*/ gpio_apb__DOT__reg_rdata;
        IData/*31:0*/ gpio_apb__DOT__reg_data_o;
        IData/*31:0*/ gpio_apb__DOT__reg_dir;
        IData/*31:0*/ gpio_apb__DOT__gpio_i;
        IData/*31:0*/ gpio_apb__DOT__open_drain;
        IData/*31:0*/ gpio_apb__DOT__pull_up_en;
        IData/*31:0*/ gpio_apb__DOT__pull_down_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__addr;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__wdata;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__rdata;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__reg_data_o;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__reg_dir;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_i;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__open_drain;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pull_up_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pull_down_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_data_o;
    };
    struct {
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_dir;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_int_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_int_typ;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_int_pol;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_int_any;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_int_sts;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_deb_th;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_deb_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_inv_in;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_inv_out;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_od_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_wr_mask;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_pu_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_pd_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_pwm_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__s_reg_pwm_cfg;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pwm_val;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_i_deb;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_i_deb_q;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_edge_pos;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_edge_neg;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gpio_edge_any;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__intr_cond;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pwm_duty_idx;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__pwm_duty_int;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__0__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__1__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__2__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__3__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__4__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__5__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__6__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__7__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__8__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__9__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__10__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__11__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__12__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__13__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__14__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__15__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__16__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__17__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__18__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__19__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__20__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__21__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__22__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__23__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__24__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__25__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__26__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__27__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__28__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__29__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__30__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__gen_deb__BRA__31__KET____DOT__deb_cnt;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk2__DOT__r;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk3__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk4__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk5__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk7__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk8__DOT__k;
    };
    struct {
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk9__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk10__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk11__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk12__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk14__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk15__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk16__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk17__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk18__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk19__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk20__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_write__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_reg_read__DOT__unnamedblk21__DOT__k;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__proc_intr_out__DOT__unnamedblk22__DOT__m;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__o;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__oe;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__i;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__open_drain;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__pull_up_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__pull_down_en;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out32;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out33;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out34;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out35;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out36;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out37;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out38;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out39;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out40;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out41;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out42;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out43;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out44;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out45;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out46;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out47;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out48;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out49;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out50;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out51;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out52;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out53;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out54;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out55;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out56;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out57;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out58;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out59;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out60;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out61;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out62;
        IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__io__out__strong__out63;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 32> gpio_apb__DOT__u_gpio_regs__DOT__s_reg_pwm_duty;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 32>, true, SData/*15:0*/, 1> __VdlyCommitQueuegpio_apb__DOT__u_gpio_regs__DOT__s_reg_pwm_duty;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_DATA_I = 0U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_DATA_O = 4U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_DIR = 8U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INT_EN = 0x0cU;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INT_TYP = 0x10U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INT_POL = 0x14U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INT_ANY = 0x18U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INT_STS = 0x1cU;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_SET_O = 0x20U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_CLR_O = 0x24U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_TGL_O = 0x28U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_DEB_TH = 0x2cU;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_DEB_EN = 0x30U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INV_IN = 0x34U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_INV_OUT = 0x38U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_OD_EN = 0x3cU;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_WR_MASK = 0x40U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_PU_EN = 0x44U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_PD_EN = 0x48U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_PWM_EN = 0x4cU;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_PWM_CFG = 0x50U;
    static constexpr CData/*6:0*/ gpio_apb__DOT__u_gpio_regs__DOT__ADDR_PWM_DUTY = 0x54U;
    static constexpr IData/*31:0*/ gpio_apb__DOT__NUM_BITS = 0x00000020U;
    static constexpr IData/*31:0*/ gpio_apb__DOT__u_gpio_regs__DOT__NUM_BITS = 0x00000020U;
    static constexpr IData/*31:0*/ gpio_apb__DOT__u_gpio_wrapper__DOT__NUM_BITS = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
